### ISSUE TITLE
bar code range error

### ISSUE THREAD

**Issue by ghost** [Pilooz/techshopio#10]
Hi,

I got an error while trying to generate bar codes in a range from 30 to 101
![capture d ecran 2017-01-24 a 16 54 34](https://cloud.githubusercontent.com/assets/25222178/22254869/0c24b12a-e256-11e6-8c8a-f283e6c71104.png)

**Comment by Pilooz** [comment]
Mmm... The error message seems to be wrong.  

Are the white spaces generating scan problem ?

**Comment by Pilooz** [comment]
Ok in release 2.1.1
